# Site settings
title: Code-Fluent
email: scottr.martin@gmail.com
author: Scott Martin
description: "Scott Martin's development blog"
baseurl: ""
url: "http://localhost/"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
