# Site settings
title: Code-Fluent
email: scottr.martin@gmail.com
author: Scott Martin
description: "Scott Martin's development blog"
baseurl: "http://scott-martin.github.io/code-fluent"
url: "http://scott-martin.github.io/code-fluent"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
